AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Despliegue de la base de datos Severless para el componente de base de datos de la solución Springfiel Car Share.
Parameters:
  DBUsername:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.

  ProcessSubNetAZ1:
    Type: AWS::EC2::Subnet::Id
    
  ProcessSubNetAZ2:
    Type: AWS::EC2::Subnet::Id
   
  DataDBSecGroup:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  SpringfieldDB:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBClusterIdentifier: SpringCS-cluster
      Engine: aurora-mysql
#EngineVersion: 5.6.10a
      EngineMode: serverless
      VpcSecurityGroupIds: 
        - !Ref DataDBSecGroup
      DBSubnetGroupName: !Ref myDBSubnetGroup
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: 2
        MaxCapacity: 32
        SecondsUntilAutoPause: 1000

  myDBSubnetGroup: 
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: Prueba de grupo de la BD
        SubnetIds: 
        - !Ref ProcessSubNetAZ1
        - !Ref ProcessSubNetAZ2
     
      
  

      